
## FIRST LINE/ROW: Info & Status
# First param ─┌
[username]
format = " [$user]($style)"
style_user = "bold bright-blue"
style_root = "bold bright-blue"
show_always = false

# Second param
[hostname]
format = "@[$hostname]($style) in"
style = "bold bright-blue"
trim_at = "-"
ssh_only = true
disabled = false

# Third param
[directory]
format = " [$path]($style) "
style = "purple"
truncation_length = 0
truncate_to_repo = true
truncation_symbol = "repo: "

# Before all the version info (python, nodejs, php, etc.)
[git_status]
style = "white"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"

# Last param in the first line/row
[cmd_duration]
min_time = 1
format = "took [$duration]($style)"
disabled = false

## SECOND LINE/ROW: Prompt
# Somethere at the beginning

# Prompt: param 2 └─
[character]
success_symbol = " [❯](bold bright-blue)"
error_symbol = " [❯](bold bright-blue)"

# SYMBOLS
[status]
symbol = "🔴"
format = '[\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
map_symbol = true
disabled = true

[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "

